#include <stdio.h>
/*
*	Very simple code that I wrote to make my profile picture on GitHub 
*	To make this ASCII art I used Ascgen2-2.0.0, you can find this program easyly to download
*/
int main(){

  printf("BBQBQBQBBBBBQBBBQBQBBBQBQBQBQBQBQBBBQBQBQBBBQBQBBBQBBBQBQBQBBBQBQBQBQBQBBBBBQBBBBBQBBBBBBB\n");
  printf("BBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBQBBBQBBBBBBBBBBBQBQBBBBBBBQBQBBBBBBBQBB\n");
  printf("QBBBBBBBQBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQBQBBBBBQBBBBBQBQBQBQBBBBBQBBBQBBBBBBB\n");
  printf("BBBBBBBBBBBBBQBBBBBQBBBBBBBBBBBDbKQQBBBBBBBBBBBQBBBBBBBQBBBQBBBQBBBBBBBBBBBBBBBQBBBBBBBBBB\n");
  printf("QBBBBBBBBBBBQBBBBBBBQBBBQBBBQBDJJvrdBBBBQBQBBBBBBBBBBBBBBBQBBBQBQBBBBBBBBBQBBBBBBBBBBBBBBB\n");
  printf("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBDIXsrigBBBBBBBBBBBBBBQBQBBBQBBBBBBBBBQBQBBBDPSSBBBBQBBBBBBBB\n");
  printf("QBBBBBBBBBBBBBBBBBBBBBBBBBBBBBMKK27riQBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBQ5r777:rQBBBQBBBBBQB\n");
  printf("BBBBBQBBBBBBBBBBBBBBBBBBBBBBBBB5X1Y7rrBQBBBBBBBQBBBBBBBQBBBQBBBBBBBQBZu777vi:.uBBBBBBBBBBB\n");
  printf("QBBBBBBBQBBBBBBBQBBBBBBBQBBBBBQSIU7v7rvBBBBBQBBBBBBBQBBBBBQBBBQBBBBBSv7Juu7ii:rBBBBBBBQBBB\n");
  printf("BBBBBBBQBBBBBBBQBBBBBBBBBBBBBBBUXUvrv777BBBBBBBBBQBBBBBBBBBBBBBBBBgu77JsuYsvr:.QBBBQBBBQBB\n");
  printf("QBBBQBQBQBQBBBQBQBBBBBBBQBBBBBQu22Y7irr7rqBBBBBBBBBBBBBBBBBBBBBBqu7r7uYv7v77rr.PBBBBBBBBQB\n");
  printf("BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBBv7rsuUuUjJvsuI5PPMMRMQRBBBBBQBBgLvv:rusv77irrvv:YBQBBBBBBBB\n");
  printf("QBBBBBBBBBBBBBBBBBBBQBBBBBQBBBSvrs5KqPSXIIUjLY7v7svL777vvJYUUjvv7:ijL7r7rriirvi7QBQBQBBBBB\n");
  printf("BBBBBBBQBBBBBQBBBBBBBBBBBBBBB2sIPqKSK5512UuJU1UuU152212sJsv:rvJr::Jvr::...:iv7i:BBBBBQBBBB\n");
  printf("QBBBQBBBBBBBBBBBQBBBBBBBBBBEuIXPqqXSIIU1jsLsYuj115I55X5IJjuYii::isjJL7:. .:7Y7:iBBBBBBBBQB\n");
  printf("BQBBBBBBBBBBBBBBBBBBBBBBdI52qKPqPKqXSUUJs7Lsuj1J1U1u112u11IIIi::rvss27. ..ivsvrrBBBBBBBBBB\n");
  printf("QBQBBBBBBBBBBBBBQBBBBgXI2KXqSKKZbZdqISus7Y1UJjsss2uJJ1u2UU1U2KUr:rvY:. ..:7UJviRBBBBBBBBQB\n");
  printf("BBBBBBBBBBBBBBBBBBBZXIXKPqP55XEPbPdPSUj7vu2J1uUJUuU1UuuuUu2U1IqIY7r   ..ivII1ijBBBBBBBBBBB\n");
  printf("QBBBBBBBQBBBBBBBBBbXSqPEPPPDZZqqPbqPU1LvjjsU2SXqII1UJ2su12UIu21SSIr:: :7YYvi.:sBBBBBBBQBBB\n");
  printf("BBBBBBBBBBBBBBBBB25ISKdPZbPPDE5SPqKusvvvYL2XbKPXPK5uj7vsjuUUIUI2SSXIu7vLjJuiYvsBBBBQBBBBBQ\n");
  printf("QBBBQBBBBBBBBBQBbISPPPPEL.   :sqPI1jssvLv2KbPPSKbbKX2ULss1jIU1uSIXXqKKjv7Lv7rivBBBBBBBBBBB\n");
  printf("BQBBBQBQBBBBBQBBIKgMBRgPv:i.. .qSjUI5JjUIIPKPPKdgEgbbqXJssJJuuU12IKSPqq1L7vii.jBBQBBBBBBBB\n");
  printf("QBBBBBBBBBQBBBBgSMQQQMRs5:.   rK5qqP25XPISSqPdU:  .rUbSS1Juuu12I55U5ISXX2jYi..KBBBBBQBQBBB\n");
  printf("BBBBBQBQBBBBBBBXEQQRMbgj7.  .uDXKSq2XKP5U121v: rI7   .JYUj2u21II211121SI521Li.BBBBBQBBBQBB\n");
  printf("QBBBBBBBBBBBBBZdRQgREXSXuv7KMMKX5PqPPPKIL7i.  SB.      iL1j2UIU51Uu2U2UIU2UUr:QBBBBBQBQBBB\n");
  printf("BBBQBBBBBBBQBBPgRDRgE1I5bDQDPSPqPPPKPXKXU77.  u7     .r5SII255S2I2522U2UI1U1siBBBBBBBBBBBB\n");
  printf("QBBBBBBBBBBBBdZRggDgEEqgRMEddEbbqPqqXq5SuJ15r:.i.:.:vdgbKPKEPPKPXPKPXSSKI212j7gBQBBBBBBBQB\n");
  printf("BBBBBBBBBBBBBPgEggMQBBBRDPZggPqXPPbKKXXI5j2KZPq1IIqgDKKXKqddEbdPPSqKPPPKX252U7dBBQBBBBBBBB\n");
  printf("QBQBBBQBBBBBdZgDbgQBIJrir7r7ruPDqqbPKKSX55USX525I5II125qXbbdbEq5jSXPKqKqKqXS2vDBBBQBBBQBBB\n");
  printf("BBBQBBBBBBBQXdZDgBB       .   :vgdEPZPq5X55SdPqXXjI5X2S5qPdPdbEPPqbKqKqPPKqSIvgBBBBBBBBBBB\n");
  printf("QBQBBBQBBBBgPb5PRBg             XMZgbdPPXKSqKPbZdZbPSKSKKPPbPddZEZPPPdqqKqXq5JQBBBBBBBBBBB\n");
  printf("BQBBBBBBBBBZMDZDMRKi....       :XEEbPPEqPqPqPPdqPPZdbPPPPPPqPKPPPqPKqXPKqXSUJLBBBBBQBQBBBB\n");
  printf("BBBBBBQBBBBdZEPgDdI. . ...    .YKK2II52X2SXqKPqPqEPdbEPbXqqPqPqqKqXKSXI522UUrbBBBBBBBBBBBB\n");
  printf("BBBBBBBQBBQ5dPbKq5jr:.  .  .:iuJK1SSPKPXSUKPdqPKKSKXPPEddqPPPqPSX55252212UILsBBQBBBBBBBBBB\n");
  printf("QBQBBBBBBBRPDgEdSjriii.....:i7J5j5sSU5IU252PqPqPXqqPXqKPPKSKSq5S11uIUIIK5SurPBBBBBBBQBBBBB\n");
  printf("BBBBBBBBBBBPDZgbquriiii:ri:::rYuJu122jI2S2I5KSS5X5XXqS2uIIX5S2U1I2K5KSq5IjJrgBBBBQBBBBBBBB\n");
  printf("QBBBBBBBBBQPbgEPPbSi.     .:::vu2IU22IKEKXUjJIS555II22U55X55U22XXPXqXXII22s7BBBBBBBBBBBBBB\n");
  printf("BBBBBQBQBBBbdEbbEgQi...       .i1SbSK5J7r::iuJI5S221U1XKP55U25qPdPPKPqPSK5YYBBBBBBBBBBBBBB\n");
  printf("QBBBBBBBBBQQqEdDbPbPvr......      :.     ..r1Iu522U55qXK5XSXXPKPKqSKKPXXUJibBBBBBBQBBBBBBB\n");
  printf("BBBBBBBBBBBBdqDEEPbPDXv:i:iiiii..  :i:iirv2IXKK2IU5XPSKISSqSSSK5XIX552IUI7vBBBBBBBBBBBBBBB\n");
  printf("BBBBBBBBQBQBQqPgZZPPPbXYi7vvvu2u7LUuYsJUU5XqXXII122SI55X5X5S552S5XXXU2UUvrDBBBBBQBBBBBBBQB\n");
  printf("BBBBBBBBBBBQBMPPdPPSqPEP5j552UKS52KI5XPKPXq55UI252Iu22I5S5PPKSK552I1UUuLisBBBQBBBBBBBBBBBB\n");
  printf("BBBBBBBBBBBBBBdXPdqPSPqbdEPPKXSK5SIS252SU111u11IUI1IU52SXPKPPq2I5IJ1uu7r2BBBBBBBBBBBBBBBBB\n");
  printf("BBBBBBBBBBBQBBBPKPbqqqPSKKPSX2SI5u2UIUU1UuUu1uUu2U5KPXK5KSXIKSKIIU2UuvrSBQBBBBBBBBBBBBBBBB\n");
  printf("BBBBBBBBBBBBBBBBq25qKbKKSqISSqSKIUUX2Uj22I1212U2IPSXKPPqXKI51U222I2U77bBBBBBBBBBBBBBBBBBBB\n");
  printf("BQBBBQBBBBBBBBBBBD5jSKPSK5555IK55UUUSIIuIUI1S225XXPPPXKSKKSUI2S11sJ7KBBBBBBQBBBBBBBBBBBBBQ\n");
  printf("QBBBBBBBQBBBBBBBBBBDUuUSSX5X2S2IU5UU12IIu5U21UJ2XK5KXK5KIUJ2SXUJvj1MBBBBQBBBQBBBBBBBBBBBBB\n");
  printf("BBBBBBBBBBBBBBBQBBBBBZX2usUUI2S25UI15UIuu22UU12uI2uu2U1J1u211sJ2DQBBBBBBBBBBBBBBBBBBBBBBBB\n");
  printf("QBBBBBBBQBBBBBBBQBQBBBBBQDX2ujLju21ujI1ujjuUJuJuss7v7vvsvYJUUEBBQBBBQBBBBBBBBBBBBBBBBBBBBB\n");
  printf("BBBBBBBQBQBBBBBBBBBBBBBBBBBQBZKUUjj77r77Lr777r77v77vU5qdDgBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBB\n");
  printf("QBBBBBBBQBBBBBBBBBBBBBQBQBBBBBBBQBBBBQQBBBQBQBBBBBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBQBQB\n");
  printf("BBBQBQBBBBBBBBBBBBBBBQBBBBBBBBBBBQBQBBBBBQBBBQBBBQBBBBBBBBBQBBBBBBBBBBBBBBBBBBBBBBBBBBBBBB\n");
  printf("BBBBBBQBQBBBBBBBBBBBBBBBBBBBQBBBBBBBBBBBBBBBBBQBBBBBQBQBBBBBBBBBBBBBBBBBBBBBBBBBQBBBQBBBBB\n");
  
}
//wow, such code, much picture
